version: "2"
services:
  db:
    image: kiasaki/alpine-postgres
    environment:
      POSTGRES_PASSWORD: palantir
      POSTGRES_USER: palantir
      POSTGRES_DB: atlas

  timelock1:
    hostname: "timelock1"
    build: ../atlasdb-timelock-server
    environment:
      - HOSTNAME=timelock1
    ports:
      - "3828"
    depends_on:
      - db

  timelock2:
    hostname: "timelock2"
    build: ../atlasdb-timelock-server
    environment:
      - HOSTNAME=timelock2
    ports:
      - "3828"
    depends_on:
      - db

  timelock3:
    hostname: "timelock3"
    build: ../atlasdb-timelock-server
    environment:
      - HOSTNAME=timelock3
    ports:
      - "3828"
    depends_on:
      - db

