version: '2'

services:
  cassandra:
    image: palantirtechnologies/docker-cassandra-atlasdb:latest
    container_name: atlas_perf_cassandra
    ports:
      - "9160:9160"
      - "9042:9042"
      - "7199:7199"
    environment:
      - LOCAL_JMX=no
      - MAX_HEAP_SIZE="2G"
      - HEAP_NEWSIZE="400M"
