version: '2'
services:
  jepsen:
    build:
      context: ./docker
      dockerfile: Dockerfile-control
    links:
      - n1
      - n2
      - n3
      - n4
      - n5
    volumes:
      - ./:/atlasdb
    command: [bash, -c, initialize_known_hosts.sh && cd /atlasdb && LEIN_ROOT=true lein test]

  n1:
    build:
      context: ./docker
      dockerfile: Dockerfile-node
    privileged: true

  n2:
    extends: n1

  n3:
    extends: n1

  n4:
    extends: n1

  n5:
    extends: n1
